### ISSUE TITLE
prodikeys pc-midi cf0040 driver and application cd

### ISSUE THREAD

**Issue by thanhtam-h** [CrazyRedMachine/Prodikeys64#5]
Thank you for great work,
Althought I still couldn't get music function of my keyboard work now, I will try it again on other PC.
Btw, do you happen to have the original driver and application cd? Could you share the iso file? I appreciate it.

**Comment by CrazyRedMachine** [comment]
hi,
a google search for "prodikeys driver" seems to bring a result from vogonsdriver which seems to be the full cd. also looks like creative.com still has an archive

beware it will only work on a 32bit OS.

**Comment by thanhtam-h** [comment]
Thanks, 
Actually cd from vogonsdriver is driver and application for 'Creative Prodikeys DM (PS/2)', not USB version. I am looking for  pc-midi cf0040 with USB interface.

**Comment by CrazyRedMachine** [comment]
then maybe you'll have better luck on creative website

**Comment by thanhtam-h** [comment]
Thanks, I have managed to get your application worked.
